_wandb:
    value:
        cli_version: 0.22.0
        e:
            95f8f0c2oyxhwu1jegc0vbi66qq7ps5b:
                args:
                    - --data
                    - dataset\aquarium_dataset\data.yaml
                    - --epochs
                    - "20"
                    - --batch
                    - "16"
                    - --imgsz
                    - "640"
                    - --model
                    - yolov8n.pt
                    - --project
                    - yolo_streamlit
                    - --name
                    - run_1761053277
                    - --device
                    - "0"
                    - --save_examples
                    - outputs/examples
                codePath: Bureau\yolo_training\train_yolo.py
                codePathLocal: train_yolo.py
                cpu_count: 14
                cpu_count_logical: 20
                disk:
                    /:
                        total: "509793865728"
                        used: "422991622144"
                email: ghoufranealoui2021@gmail.com
                executable: C:\Users\ghofr\anaconda3\envs\anaconda-ml-ai\python.exe
                git:
                    commit: 3536f49f925b57a63476033647abad6662ef1663
                    remote: https://github.com/ghofran190/IoT-Security.git
                host: LAPTOP-956CPM7U
                memory:
                    total: "25376313344"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\ghofr\Bureau\yolo_training\train_yolo.py
                python: CPython 3.11.13
                root: C:\Users\ghofr\Bureau\yolo_training
                startedAt: "2025-10-21T13:28:08.193438Z"
                writerId: 95f8f0c2oyxhwu1jegc0vbi66qq7ps5b
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 16
            "4": 3.11.13
            "5": 0.22.0
            "8":
                - 3
            "12": 0.22.0
            "13": windows-amd64
batch:
    value: 16
epochs:
    value: 20
imgsz:
    value: 640
model:
    value: yolov8n.pt
